### ISSUE TITLE
What does this function mean?

### ISSUE THREAD

**Issue by b3326023** [rmantena/Myo_gestureArmBand_experiments#1]
Can you explain what is the mean of this function? Why to sum array[1] - array[0] ?
```
def wl(array):
    sum = 0
    for a in range(0,len(array)-1):
        sum =+ array[0+1] - array[0]
    return sum
```

**Comment by rmantena** [comment]
![image](https://user-images.githubusercontent.com/22087772/39609041-10a98a20-4f03-11e8-9bd0-42a8c2b01caf.png)

**Comment by rmantena** [comment]
I tried to implement the below function from linked research paper. Seems like I made a terrible mistake. 

![image](https://user-images.githubusercontent.com/22087772/39609045-1e56e32a-4f03-11e8-8c88-8b232fb3e549.png)

http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7748960

**Comment by rmantena** [comment]
Fixed with the below commit 

https://github.com/rmantena/Myo_gestureArmBand_experiments/commit/9318fe68bf305623a70a0eeeae223f53b802e736
